{% set name = "islpy" %}
{% set version = "2018.1" %}
{% set sha256 = "da49759d3a0266f1ea0b50fd631ef9c27b5db5fe32ac056f20dc7f9f916f96d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - use_gmp.diff
    - gen_wrap.diff

build:
  number: 0
  skip: True  # [win and py27]

requirements:
  build:
    - python
    - setuptools
    - six
    - cffi
    - isl 0.20    # [win]
  run:
    - python
    - cffi
    - six

test:
  requires:
    - pytest
  imports:
    - islpy

  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: http://github.com/inducer/islpy
  license: MIT
  summary: 'Wrapper around isl, an integer set library'

  description: |

    islpy is a Python wrapper around Sven Verdoolaege's
    [isl](http://www.kotnet.org/~skimo/isl/), a library for manipulating
    sets and relations of integer points bounded by linear constraints.

    Supported operations on sets include

    -   intersection, union, set difference,
    -   emptiness check,
    -   convex hull,
    -   (integer) affine hull,
    -   integer projection,
    -   computing the lexicographic minimum using parametric integer
        programming,
    -   coalescing, and
    -   parametric vertex enumeration.

    It also includes an ILP solver based on generalized basis reduction,
    transitive closures on maps (which may encode infinite graphs),
    dependence analysis and bounds on piecewise step-polynomials.

  doc_url: https://documen.tician.de/islpy
  dev_url: https://github.com/inducer/islpy

extra:
  recipe-maintainers:
  - inducer
