{% set name = "islpy" %}
{% set version = "2024.2" %}
{% set sha256 = "52d4dc4f020894cb93636f64744c087df58ab9f97676d8f1dcb4d510249bc7ab" %}
{% set build_num = 1 %}

{% if with_barvinok == "False" %}
{% set build_num = build_num + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_num }}
  track_features:
    # deprioritise the barvinok build
    - islpy_barvinok  # [with_barvinok]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - nanobind                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - m2-sed                                 # [build_platform == "win-64"]
  host:
    - python
    - pip
    - nanobind
    - isl >=0.27
    - setuptools
    - scikit-build
    - pcpp
    - barvinok  # [with_barvinok]
    - libxcrypt  # [linux]
  run:
    - python
    # Need the same version of isl we had when the package was built
    - {{ pin_compatible("isl", max_pin="x.x.x") }}
  run_constrained:
    # when barvinok is installed deprioritise the non-barvinok build
    - barvinok <0.0a0  # [not with_barvinok]


test:
  requires:
    - pytest
  imports:
    - islpy

  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: https://github.com/inducer/islpy
  license: MIT
  license_file:
    - doc/misc.rst
  license_family: MIT
  summary: Wrapper around isl, an integer set library

  description: |
    islpy is a Python wrapper around Sven Verdoolaege's
    [isl](https://libisl.sourceforge.io/), a library for manipulating
    sets and relations of integer points bounded by linear constraints.

    Supported operations on sets include

    -   intersection, union, set difference,
    -   emptiness check,
    -   convex hull,
    -   (integer) affine hull,
    -   integer projection,
    -   computing the lexicographic minimum using parametric integer
        programming,
    -   coalescing, and
    -   parametric vertex enumeration.

    It also includes an ILP solver based on generalized basis reduction,
    transitive closures on maps (which may encode infinite graphs),
    dependence analysis and bounds on piecewise step-polynomials.

  doc_url: https://documen.tician.de/islpy
  dev_url: https://github.com/inducer/islpy

extra:
  recipe-maintainers:
    - matthiasdiener
    - inducer
