travis:
  secure:
    BINSTAR_TOKEN: IsZUZDRC+T0pU+DuXwgRd7SutRivICkVKXBkhKADgq5CdNgktEymYwWngCgHx+XuO3fX7qWy7OTaMSQDCU28fBVp8yc3pMZUXeoT+fnIl4dFg0yxM39ZBOSOWN+dZsVbwWIw8LP8Grnmy09lnmEEld9M8wNAJWRX9NansqkoW1Jq27zEyiBlFb+Zyg9CersgYLf6b0g6rjJjCOzwBrsfD+7ffDjcaD4Zm3u4uApdkIAhQ/mnaj/dXEkNE8bJPPDpaB1RMneQws11Z4+3jbAxKiQ8+dHe6bDewuoUnfYJ93e6FZxQ1J0P2uTWdmCE7G6rCUguux3fEy30mX/1FRleuYgfCzxkxNxtv8cIy4QNd0SuL61m1jUOKSLYzNr5Jn434XccABRCooRqZ6+37k/xmHYCQ5AgPXULDHpBgLLl1Npaz7NsL0T+ja9jWpIoWu+KekeByp4zcWnGZrtRzVhWWNU3LTFvxtbiAB+jTzYJGweLavDwLKr4dDcrT1xVjqX8gt/8zh00MPNnwKwqTpehsU0+Gb3D/OzsHCLVhT/zAsg/5hNkuNf87tQtKZESKQT7Zr3HnU06a+kmstnl/lqGTX6apgX2O9sg1dlztzZUe1rdbXJOEuDR5U6tnAd4LaGBf4vqjDbCWj9x79rq7/K9azMBPlGd4neIFD4nNiXHfHI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
