appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dzvpYPNAok/NkIQdDVJY9GXgVQ/xcojbuzUWyvrq3v1YY273co03hL6U4WIvUrFXgNMV3IHzKGz4x0YFJkgpS2HOFT6Y6nS7aTmjFqEoGoShCpj0/J/rk4RQLpo/WFQ0M3ImTXf9BKPalLN3aLEuqf4aZmQJqmzeCmEVcVsIBmgBMFUIW7QJ+/Y5Cew1HF0JrC/ClOcsjtTkHUnYTdn5tzYG3P8aBbawpaHLI2ARYf5zyR+mEZbh0BuzYv7/WcMwdtOEJtcOPe9VamaDTWXX1oERWUTQRMa4PbOFZqtpwQQxFgOSUzJiwvACYOh/C5g5x60MFTqix27IhePEy+qCtB6PocvzzMYEhLaZb4K3HwXBd6AGgGwkmPbCAdhUIy4YxVXfprK6D7XhZiiooWpgTRqPSQFHY2NP7SWpV1MRIYowJ5LPmqGPweowmsPCPw069/DSLio/f8j7QAuRir6/zCv3KiQ/A04iTIvc6EqIudlTTC/gxbhEY/ux++dPhQ6wH0rt+qUijVq0Ki3VSSnmcC0A05n4rpY/FgHDU/s7GXZu7mJQMlppzW6UUMOQJSK9D1zERsJICrxyxGBI6UK1q3/scCsctU1D7JPU6ly4EaMWw0g2gEthcHd6c0PoN5NqMnBtG3InpoB2+bIkwwXOKlcdV1wXlERsF7vizCUBMLw=}
